apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
  namespace: fastfood
data:
  DATABASE_URL: "postgresql://postech:postech-password@fastfood-postgres-service:5432/fastfood"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ENVIRONMENT: "production"
  DEBUG: "false"
  CORS_ALLOW_ORIGINS: "https://fastfood-murex.vercel.app"
  API_PREFIX: "/v1"
  PROJECT_NAME: "FastFood API"
  VERSION: "1.0.0"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-init-scripts
  namespace: fastfood
data:
  init.sql: |
    -- Create database if not exists
    CREATE DATABASE IF NOT EXISTS fastfood;
    
    -- Create categories table
    CREATE TABLE IF NOT EXISTS categorias (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        nome VARCHAR(100) NOT NULL UNIQUE,
        descricao TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert default categories
    INSERT INTO categorias (nome, descricao) VALUES
    ('burgers', 'Hambúrgueres e lanches'),
    ('drinks', 'Bebidas e refrigerantes'),
    ('sides', 'Acompanhamentos'),
    ('desserts', 'Sobremesas')
    ON CONFLICT (nome) DO NOTHING; 