apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastfood

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- postgres-persistent-volume.yaml
- postgres-deployment.yaml
- app-deployment.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: fastfood
  version: v1.0.0 