services:
  - type: web
    name: fastfood-api
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ALLOW_ORIGINS
        value: https://fastfood-murex.vercel.app,https://fastfood-vwtq.vercel.app
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeploy: true 